name: Silent Journey Deploy
run-name: ${{ github.ref_name }} deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build

    permissions:
      contents: read
      id-token: write
      pages: write

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4