name: Silent Journey ci
run-name: ${{ github.ref_name }} CI


on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - 'vite.config.ts'

  workflow_dispatch:


jobs:
  build:
    uses: ./.github/workflows/build.yml